version: '3'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'shortener'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: lasit/url-shortener
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
  angular-service:
    container_name: url-shortener-client
    build: ./url-app-client

    ports:
      - '4200:4200'
volumes:
  data:


